### ISSUE TITLE
how to detect a rotational rectangle?

### ISSUE THREAD

**Issue by helloxueen** [see--/keras-centernet#12]
how to detect a rotational rectangle using keypoint detection?

**Comment by zstu-lly** [comment]
I think you can regress the vector from center to four corners of a rectangle.

**Comment by LinyeLi60** [comment]
> 
> 
> how to detect a rotational rectangle using keypoint detection?

I think you can regress the vector from center to four corners of a rectangle.

**Comment by see--** [comment]
You could add an additional head to regress the angle (like the one to regress the offsets). It's interesting but not part of CenterNet, which only supports coordinate aligned boxes.
