### ISSUE TITLE
Data Format Convention used by the HourglassNetwork

### ISSUE THREAD

**Issue by RACHANAMOVVA09** [see--/keras-centernet#14]
There is a link which is being mentioned: ~/.keras/keras.json. I'm unable to access this link and this is mentioned in the hourglass.py file(under def HourglassNetwork; Note that the data format convention used by the model is the one specified in your Keras config at `~/.keras/keras.json`.). How do I find the data format for the HourglassNetwork architecture?

**Comment by see--** [comment]
It doesn't depend on this repo. It's the same as your keras setting.
