### ISSUE TITLE
Pytorch to keras weight mapping

### ISSUE THREAD

**Issue by PushparajaMurugan** [see--/keras-centernet#18]
Hi, YOu have done a grt job. Could you pls share the scripts for mapping pytoch weights to keras framework. Pytorch2keras is not working propoerly for the arch.

Thanks

**Comment by see--** [comment]
Thanks for reporting that pytorch2keras does not work here. Could you check if #16 solves your issue? Let me know if it works, so that I can merge or recheck.

Edit: Do you mean the pull-request or the pytorch2keras repository? https://github.com/nerox8664/pytorch2keras

**Comment by PushparajaMurugan** [comment]
Hi 
Its the" pytorch2keras repository".

I have tested the other models using that repo and was unable to run this repo on your arch.  The problem that I have faced is, it always gives the same probability scores and class number. I will check #16 and let you know the outcomes.
Thanks,
