### ISSUE TITLE
hello,Thank you for your code.I want to know when the training code will be updated.

### ISSUE THREAD

**Issue by LCWdmlearning** [see--/keras-centernet#3]
hello,Thank you for your code.I want to know when the training code will be updated.
thanks a lot！！！

**Comment by see--** [comment]
Probably within this month. It is not easy to build a fast training pipeline with keras. I.e. `fit_generator` & `keras.utils.Sequence` is slow. If you need a good (TensorFlow) object detector right now, take a look at tensorpack FasterRCNN: https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN. I will close this issue as it is tracked by #2.

**Comment by LCWdmlearning** [comment]
Thank you for your reply. Maybe it doesn't matter if it's slow. I'm going to retrain on a small training set.
My own training code(keras) is not good， So I want to see your training code.
Finally, thank you for your sharing.












------------------ 原始邮件 ------------------
发件人: "see--"<notifications@github.com>; 
发送时间: 2019年5月16日(星期四) 下午2:51
收件人: "see--/keras-centernet"<keras-centernet@noreply.github.com>; 
抄送: "李灿伟"<413645892@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [see--/keras-centernet] hello,Thank you for your code.I want toknow when the training code will be updated. (#3)




Probably within this month. It is not easy to build a fast training pipeline with keras. I.e. fit_generator & keras.utils.Sequence is slow. If you need a good (TensorFlow) object detector right now, take a look at tensorpack FasterRCNN: https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN. I will close this issue as it is tracked by #2.

**Comment by white2018** [comment]
> Thank you for your reply. Maybe it doesn't matter if it's slow. I'm going to retrain on a small training set. My own training code(keras) is not good， So I want to see your training code. Finally, thank you for your sharing.
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "see--"<notifications@github.com>; 发送时间: 2019年5月16日(星期四) 下午2:51 收件人: "see--/keras-centernet"<keras-centernet@noreply.github.com>; 抄送: "李灿伟"<413645892@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [see--/keras-centernet] hello,Thank you for your code.I want toknow when the training code will be updated. (#3) Probably within this month. It is not easy to build a fast training pipeline with keras. I.e. fit_generator & keras.utils.Sequence is slow. If you need a good (TensorFlow) object detector right now, take a look at tensorpack FasterRCNN: https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN. I will close this issue as it is tracked by #2. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.



> Thank you for your reply. Maybe it doesn't matter if it's slow. I'm going to retrain on a small training set. My own training code(keras) is not good， So I want to see your training code. Finally, thank you for your sharing.
> […](#)

@LCWdmlearning Could you share your training code please? That would be appreciated.

Thanks a lot
