### ISSUE TITLE
0it [00:00, ?it/s] no output

### ISSUE THREAD

**Issue by caikw0602** [see--/keras-centernet#8]
There is no output and display "0it [00:00, ?it/s]" when I run the file "ctdet_image.py" with Pycharm. How can i figure it out please? Would you please give me some help please? Thank you very much.

**Comment by see--** [comment]
I don't use Pycharm and thus can't help you with it :). The script didn't find the image(s) ->`0it`. Make sure you run it from the repo root dir (i.e. use `keras_centernet/bin/ctdet_image.py`) and that the image (s) exist.

**Comment by caikw0602** [comment]
Thank you very much for your reply.Further, I also tried running the net without pycharm, unluckily OOM error occurred. My GPU is Geforce 970M with 3G memory. Is it because that the hourglass net is too big, my GPU can not afford it?

**Comment by see--** [comment]
I works with 4GB memory. Try `--inres 384,384` to reduce the memory usage. Good luck!

**Comment by caikw0602** [comment]
Yes, I also tried that size. The OOM error still exists. Thank you for your kindly reply.

**Comment by azhaoaigaga** [comment]
@see-- Hello, I also use a 4gb gpu, but it is over to always create the tensorflow device, why?
