### ISSUE TITLE
The predicted score is 0.0

### ISSUE THREAD

**Issue by zhongdixiu** [see--/keras-centernet#9]
When I run the keras_centernet/bin/ctdet_image.py, and input demo.jpg (or demo2.jpg), the predicted score is always 0.0, How can I solve this problem?Thanks very much!

**Comment by see--** [comment]
I works fine for me. Feel free to reopen, if you can provide a minimal example to reproduce the issue.
`python keras_centernet/bin/ctdet_image.py` -> https://github.com/see--/keras-centernet/blob/master/assets/out.demo.jpg
